### ISSUE TITLE
A details of GNN-SL

### ISSUE THREAD

**Issue by wjczf123** [ShuheWang1998/GNN-SL#1]
Hi, shuhe.

I have a question about implementation detail.

Is this model trained end-to-end or two-stage? 
1. If it is two-stage, we first train vanilla SL model and then train the parameters of the graph. 
2. If it is end-to-end, the datastore will change causing a high time overhead.

**Comment by ShuheWang1998** [comment]
> 

The model is trained two-stage. As you mentioned, you need to train the vanilla SL model and the constructed graph in order. 

In fact, we once attempted to just train an end-to-end model and you may find relevant codes in this repo. However, this strategy exists many problems, such as high time consumption as you said.

**Comment by ShuheWang1998** [comment]
> Hi, shuhe.
> 
> I have a question about implementation detail.
> 
> Is this model trained end-to-end or two-stage?
> 
> 1. If it is two-stage, we first train vanilla SL model and then train the parameters of the graph.
> 2. If it is end-to-end, the datastore will change causing a high time overhead.

The model is trained two-stage. As you mentioned, you need to train the vanilla SL model and the constructed graph in order.

In fact, we once attempted to just train an end-to-end model and you may find relevant codes in this repo. However, this strategy exists many problems, such as high time consumption as you said.

**Comment by wjczf123** [comment]
OK. Thank you very much for your reply.

**Comment by wjczf123** [comment]
Hi, shuhe. I am very sorry to disturb you again.
I have another detailed question about Vanilla SL model. 

Does two-stage training mean that the parameters of vanilla SL model are fixed or variable during the GNN training process?
And have you explored how much this affects the final result?

Thanks.

**Comment by wjczf123** [comment]
I am looking forward to your reply.

**Comment by ShuheWang1998** [comment]
> wjczf123

Sorry for the long time of no reply. 

The two-stage training means that (1) we only train the bert-based sequence labeling task; (2) we leverage GNN on the constructed graph with k-nearest neighbors retrieved by the bert-based SL model.

For the second stage, we fix the retrieved k-nearest neighbors (including its embedding), and only train the GNN to find a well weigh allocation among the input sentence and its k-NN.

We have not conducted experiments to analyze the affects of the two-stage training. 
We once attempted to just train an end-to-end model, but both the high training consumption and the imbalance between the bert-based SL and the GNN prevent us to do this.
And how to leverage a one-stage training is what we are going to do.

**Comment by wjczf123** [comment]
Thanks for your reply. Very nice work.
